version: '3.1'

services:
  nginx:
    container_name: api_nginx
    image: nginx:stable
    ports:
      - ${DOCKER_HTTP_PORT}:80
      - ${DOCKER_HTTPS_PORT}:443
    working_dir: /src
    volumes:
      - ./src:/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
    links:
      - api_database

  api_php:
    container_name: api_php
    build: ./docker/php
    working_dir: /src
    volumes:
    - ./src:/src
    - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    - $HOME/.composer/cache:/root/.composer/cache
    networks:
      - code-network
    links:
      - api_database

  api_database:
    container_name: api_database
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
    ports:
      - ${DOCKER_DB_PORT}:3306
    volumes:
    - mysql-data:/data/mysql/db
    networks:
      - code-network

volumes:
  mysql-data:
    driver: local

networks:
  code-network:
    driver: bridge
